### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by drdoof2019** [b31ngd3v/MyIGBot#1]
I did this steps:
1) pip install myigbot
2) write this to a python file

```
from myigbot import MyIGBot
bot = MyIGBot('usrname', 'pass')  # Login Information (if you're account has 2 Factor Auth. The Bot Will Ask You The Code.)
a=bot.like('https://www.instagram.com/p/CHqtHbkB6KE/')
print(a)
```

but unfortunately

>  ←[91m[✗] Login Failed!←[0m 

this error occured.
What's wrong?

**Comment by b31ngd3v** [comment]
Try to login in your browser in incognito mode and see if it asks for any code or not. After verifing the code in your browser, run the script.

**Comment by drdoof2019** [comment]
I already did that, did not work. I can log in to my account in incognito mode but I cannot login with script

**Comment by b31ngd3v** [comment]
Soon pushing the next update of the module, in 1-2 days

**Comment by animemoeus** [comment]
I have the same problem

**Comment by animemoeus** [comment]
> Try to login in your browser in incognito mode and see if it asks for any code or not. After verifing the code in your browser, run the script.

Also not working for me

**Comment by b31ngd3v** [comment]
@animemoeus @drdoof2019 I updated the package. 
`pip install --upgrade myigbot`

**Comment by animemoeus** [comment]
> @animemoeus @drdoof2019 I updated the package.
> `pip install --upgrade myigbot`

Great

Its work for me now

**Comment by Remiphilius** [comment]
I have the same issue, despite `pip install --upgrade myigbot`

**Comment by Goodsayan** [comment]
I have the same problem and I already have version 0.2.5

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/myigbot/__init__.py", line 61, in __init__
    self.csrf_token = cookie_jar['csrftoken']
KeyError: 'csrftoken'

And on my account IG, I have a suspicious connection attempt
