### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by trashmit** [b31ngd3v/MyIGBot#12]
KeyError: "name='csrftoken', domain=None, path=None"

just tried to login and this error came up

```
from myigbot import MyIGBot

bot = MyIGBot('xxx', 'xxx')
```

**Comment by b31ngd3v** [comment]
Are you working on vps ?

**Comment by trashmit** [comment]
Nope, no reason for it to confirm or something

**Comment by b31ngd3v** [comment]
This bug is already fixed by @animemoeus If you use this repo instade of the module you'll not face the issue. I'll add the fix on the next update of the module. Thank you 😊

**Comment by trashmit** [comment]
Nope, that's not working either i'm not getting any cookies at all maybe its cause im on a mac and the user agent isn't sent in the first response?

**Comment by trashmit** [comment]
the first request *

**Comment by b31ngd3v** [comment]
@trashmit My client is using the same module on his Mac, he has no issues. So the os doesn't matter in this case.

**Comment by devtobi** [comment]
For me its not working either, also not with @animemoeus fork. Using Big Sur 11.0.1 with Python 3.9.0.

**Comment by b31ngd3v** [comment]
Hey @devtobi are you facing the same issue ?

> KeyError: "name='csrftoken', domain=None, path=None"

**Comment by animemoeus** [comment]
> KeyError: "name='csrftoken', domain=None, path=None"
> 
> just tried to login and this error came up
> 
> ```
> from myigbot import MyIGBot
> 
> bot = MyIGBot('xxx', 'xxx')
> ```

I have faced the same issue and after change `link = 'https://www.instagram.com/accounts/login/'` to  `link = 'https://www.instagram.com/'` it's working for me.

You can try to use the default link (`link = 'https://www.instagram.com/accounts/login/'`) if my solution doesn't work.

**Comment by devtobi** [comment]
> Hey @devtobi are you facing the same issue ?
> 
> 
> 
> > KeyError: "name='csrftoken', domain=None, path=None" 

Yes its exactly the same issue.

**Comment by trashmit** [comment]
My cookie jar is returning empty so I assume that's where the error is coming from I tried switching the link to both urls and it isn't working

**Comment by animemoeus** [comment]
> My cookie jar is returning empty so I assume that's where the error is coming from I tried switching the link to both urls and it isn't working

In my experience, the cookie_jar csrftoken error occurs because I use the bot too often. When I try again with another IP then it works again.

**Comment by b31ngd3v** [comment]
> My cookie jar is returning empty so I assume that's where the error is coming from I tried switching the link to both urls and it isn't working

You can try proxy, residential proxies are better for this type of work.

**Comment by animemoeus** [comment]
> > My cookie jar is returning empty so I assume that's where the error is coming from I tried switching the link to both urls and it isn't working
> 
> You can try proxy, residential proxies are better for this type of work.

Yeah, because I use cron job to run the bot every hour, I use the proxy feature.

Before using a proxy, I ofter get an error in cookie_jar csrftoken ketika bot telah berjalan selama beberapa jam.

**Comment by animemoeus** [comment]
> > My cookie jar is returning empty so I assume that's where the error is coming from I tried switching the link to both urls and it isn't working
> 
> You can try proxy, residential proxies are better for this type of work.

Yes, since I use cron jobs to run the bot every hour, I use the proxy feature.

Before using a proxy, I often get the cookie_jar csrftoken error when the bot is running for hours.

**Comment by trashmit** [comment]
I got a temporary fix to the problem by setting the csrf token in the first response manually to a random string,  it works for now but shouldn't be a permanent fix

**Comment by b31ngd3v** [comment]
@trashmit @devtobi Just Fixed The Login Issue
