### ISSUE TITLE
Suspicious login attempt

### ISSUE THREAD

**Issue by yasserN** [b31ngd3v/MyIGBot#27]
Even the simplest bot would not work as the login would fail due to instagram detecting a suspicious login attempt and requiring verification. Even after verifying the warning, it would still block out the bot every time. What should I do? I have tried logging in using incognito, verifying, and starting up the bot, but this did not fix the issue. Does the bot not work anymore?
```python
from myigbot import MyIGBot

bot = MyIGBot( "", "")

response = bot.upload_post('testing.png', caption='Image 1')
print(response) 

```
**EDIT:**  I tried adding a 2 Factor Authentication to my account, but it still raises the suspi cious login warning, and gives me this error now:
```

Traceback (most recent call last):
  File "C:\Users\\Desktop\Personal Work\\.....\\", line 4, in <module>
    bot = MyIGBot('', '')
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\site-packages\myigbot\__init__.py", line 178, in __init__
    self.sessionid = login_response.headers['Set-Cookie'].split('sessionid=')[1].split(';')[0]
IndexError: list index out of range
```

**Comment by toza-mimoza** [comment]
Same here.

**Comment by b31ngd3v** [comment]
@n0-sound Hey, hide your credentials.

**Comment by b31ngd3v** [comment]
The bot is still functional, try to use proxy. I think your ip is flagged by Instagram.

**Comment by n0-sound** [comment]
> The bot is still functional, try to use proxy. I think your ip is flagged by Instagram.

Can you explain how to do that? I tried but got kinda lost. Sorry I'm still new to these things. And thanks for the heads up.
