### ISSUE TITLE
add return spam

### ISSUE THREAD

**Issue by online002** [b31ngd3v/MyIGBot#6]
please add error handling when returning json smap {"message": "", "spam": true, "status": "fail"}

eg try follow_count = json.loads (response) ['graphql'] ['user'] ['edge_follow'] ['count']
except

follow_count = json.loads (response) ['spam']

**Comment by b31ngd3v** [comment]
Sorry I didn't get you, can you explain a bit more, What's the issue ?

**Comment by online002** [comment]
due to frequent requests, instagram responds in json that this is spam, you can do so that the code does not break off and return spam with a message

**Comment by b31ngd3v** [comment]
Thank you for your suggestion, surely I'll add this error handling to the next version. Thanks again.

**Comment by online002** [comment]
if it doesn't make it difficult, you can write recommendations for timers to avoid spam ban

**Comment by b31ngd3v** [comment]
Need a bit help from you, can you tell me when you get this type of response and what (type of task) you're performing then ?

**Comment by online002** [comment]
```import time
from myigbot import MyIGBot
import random

bot = MyIGBot('login', 'pass')

akk = 'livesound_official'
followers_count = bot.user_followers_count(akk)

def private():
    lst_follow = bot.user_followers(akk, limit=followers_count)
    for i in lst_follow:
        time.sleep(random.randint(10, 11))
        private = bot.private_user(i) 
        if private == True:
            print(i, private)
```

**Comment by b31ngd3v** [comment]
MAN! I didn't know my api is that powerful. It successfully grabbed **66,000 usernames** 😳.

![PicsArt_11-28-08 00 19](https://user-images.githubusercontent.com/64733912/100492209-19819700-3150-11eb-817a-416cff721fad.png)
