### ISSUE TITLE
Add a function to post videos

### ISSUE THREAD

**Issue by trashmit** [b31ngd3v/MyIGBot#7]
Just a suggestion, it would be greatly appreciated and separate this repo from the other ones aside from how easy it is to use :)

**Comment by b31ngd3v** [comment]
The next update is scheduled on 10th December, we are adding 10+ more features to this api including post video/video story.

**Comment by skiesx** [comment]
> The next updated is scheduled on 10th December, we are adding 10+ more features to this api including post video/video story.

this is a much needed update.  thanks for the implementation)

**Comment by niteshprajapat** [comment]
Hey bro , I was using selenium for username and password .  If I use this :- 
response = bot.upload_story('image2.png')
print(response) 

I know I will get an error .
Then how can I use this upload_story function . 
Any idea ?

**Comment by skiesx** [comment]
@b31ngD3v hi, any update?

**Comment by linkeli-labs** [comment]
Is it possible to upload videos yet?

**Comment by b31ngd3v** [comment]
> Is it possible to upload videos yet?

No

**Comment by Gupta-Anubhav12** [comment]
Can I take this issue ?

**Comment by Gupta-Anubhav12** [comment]
hey @b31ngd3v  can you help a bit, I wisht to upload videos
if you have some potential docs for helping

**Comment by b31ngd3v** [comment]
> hey @b31ngd3v can you help a bit, I wisht to upload videos if you have some potential docs for helping

this project was sponsored by a social media influencer, but at the end of 2020 he stopped providing funds. since then this project is not actively maintained. so the features i promised will not be available. sorry.

**Comment by Gupta-Anubhav12** [comment]
I can implement the feature myself and send a PR so if I can have some reference

**Comment by b31ngd3v** [comment]
> I can implement the feature myself and send a PR so if I can have some reference

you've to reverse engineer the instagram mobile app with tools like burpsuite, and then try to replicate the requests that the app makes during a video upload.

**Comment by Gupta-Anubhav12** [comment]
Great got it
